# Generated by Django 4.2.3 on 2023-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Surname", models.CharField(max_length=50)),
                ("FirstName", models.CharField(max_length=100)),
                ("MiddleName", models.CharField(max_length=100)),
                ("Maiden_surname", models.CharField(max_length=50)),
                ("Housenum", models.CharField(max_length=50)),
                ("Village", models.CharField(max_length=50)),
                ("Barangay", models.CharField(max_length=50)),
                ("Municipality", models.CharField(max_length=50)),
                ("Province", models.CharField(max_length=50)),
                ("Rurban_code", models.CharField(max_length=6)),
                ("Sex", models.CharField(max_length=1)),
                ("Citizenship", models.CharField(max_length=50)),
                ("Contact_number", models.CharField(max_length=11)),
                ("Email_address", models.EmailField(max_length=100)),
                ("Birthdate", models.DateField()),
                ("Birthplace", models.CharField(max_length=50)),
                ("Birth_rurban_code", models.CharField(max_length=6)),
                ("Spouse_name", models.CharField(max_length=50)),
                ("Spouse_citizenship", models.CharField(max_length=50)),
                ("Father_name", models.CharField(max_length=50)),
                ("Father_citizenship", models.CharField(max_length=50)),
                ("Mother_name", models.CharField(max_length=50)),
                ("Mother_citizenship", models.CharField(max_length=50)),
                ("Been_convicted", models.CharField(max_length=3)),
            ],
        ),
    ]
