# Generated by Django 4.2.3 on 2023-07-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PRCBoardExamRegistration", "0002_rename_personalinformation_personalinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="id",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="PersonalID",
            field=models.CharField(
                default="", max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
