# Generated by Django 4.2.3 on 2023-07-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "PRCBoardExamRegistration",
            "0003_remove_personalinfo_id_personalinfo_personalid",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamHistory",
            fields=[
                (
                    "Exam_num",
                    models.CharField(
                        default="", max_length=8, primary_key=True, serialize=False
                    ),
                ),
                ("Exam_name", models.CharField(max_length=50)),
                (
                    "exam_place",
                    models.CharField(
                        choices=[
                            ("Manila", "Manila"),
                            ("Baguio", "Baguio"),
                            ("Cebu", "Cebu"),
                            ("Davao", "Davao"),
                        ],
                        max_length=10,
                    ),
                ),
                ("Date_Taken", models.DateField()),
                (
                    "PersonalID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PRCBoardExamRegistration.personalinfo",
                    ),
                ),
            ],
        ),
    ]
