# Generated by Django 4.2.3 on 2023-07-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PRCBoardExamRegistration", "0004_examhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationInfo",
            fields=[
                (
                    "Educ_ID",
                    models.CharField(
                        default="", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                (
                    "PRC_sc",
                    models.PositiveIntegerField(
                        max_length=4, verbose_name="PRC School Code"
                    ),
                ),
                ("School_name", models.CharField(max_length=100)),
                ("School_add", models.CharField(max_length=255)),
                (
                    "PRC_cc",
                    models.PositiveIntegerField(
                        max_length=4, verbose_name="PRC Course Code"
                    ),
                ),
                ("Degree_Course", models.CharField(max_length=100)),
                ("Grad_date", models.DateField()),
                (
                    "PRC_bc",
                    models.PositiveIntegerField(
                        max_length=4, verbose_name="PRC Board Code"
                    ),
                ),
                (
                    "PersonalID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PRCBoardExamRegistration.personalinfo",
                    ),
                ),
            ],
        ),
    ]
