# Generated by Django 4.2.3 on 2023-07-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PRCBoardExamRegistration", "0006_alter_educationinfo_prc_bc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="Been_convicted",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                verbose_name="Have Been Convicted?",
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("Exam_name", models.CharField(max_length=50)),
                (
                    "exam_place",
                    models.CharField(
                        choices=[
                            ("Manila", "Manila"),
                            ("Baguio", "Baguio"),
                            ("Cebu", "Cebu"),
                            ("Davao", "Davao"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ExamDate", models.DateField()),
                (
                    "Application_stat",
                    models.CharField(
                        choices=[
                            ("First Timer", "First Timer"),
                            ("Repeater", "Repeater"),
                            ("Conditioned", "Conditioned"),
                            ("Absent", "Absent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Prev_examinee",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        verbose_name="Previous Examinee?",
                    ),
                ),
                (
                    "Exam_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PRCBoardExamRegistration.examhistory",
                    ),
                ),
                (
                    "PersonalID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PRCBoardExamRegistration.personalinfo",
                    ),
                ),
            ],
        ),
    ]
