# Generated by Django 4.2.3 on 2023-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PRCBoardExamRegistration",
            "0007_alter_personalinfo_been_convicted_application",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_id",
            field=models.CharField(
                default="", max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
