# Generated by Django 4.2.3 on 2023-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PRCBoardExamRegistration", "0008_alter_application_application_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="ExamDate",
        ),
        migrations.RemoveField(
            model_name="application",
            name="exam_place",
        ),
        migrations.AddField(
            model_name="examhistory",
            name="Rev_center",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="examhistory",
            name="exam_rating",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="examhistory",
            name="exam_result",
            field=models.CharField(
                choices=[
                    ("Passed", "Passed"),
                    ("Failed", "Failed"),
                    ("Conditioned", "Conditioned"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="Civil_Stat",
            field=models.CharField(default="Single", max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="educationinfo",
            name="PRC_bc",
            field=models.CharField(max_length=4, verbose_name="PRC Board Code"),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Father_citizenship",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Father_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Maiden_surname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="MiddleName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Mother_citizenship",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Mother_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Sex",
            field=models.CharField(choices=[("M", "M"), ("F", "F")], max_length=1),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Spouse_citizenship",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Spouse_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="Village",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
